# Deploy da Aplicação Web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: geraldobl58/webapp
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          # env:
          #   - name: ASPNETCORE_HTTP_PORTS
          #     value: "8080"
          #   - name: ConnectionStrings__DefaultConnection
          #     value: "Host=postgre;Database=webapp;Username=webapp;Password=Passw0rd2024!"
          # ports:
          #   - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080
      #nodePort: 30000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  ingressClassName: nginx
  rules:
    - host: development.ogeraldoluiz.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: webapp
                port:
                  number: 80
