name: CI/CD Pipeline
run-name: Pipeline CI/CD executed by ${{ github.actor }} in ${{ github.run_number }}

on:
  push:
    branches: [develop]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  # Continuous Integration (CI)
  CI:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      # Cache Node.js dependencies
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the application
      - name: Build
        run: npm run build

      # Run linting
      - name: Linting
        run: npm run lint


  # Test
  Tests:
    needs: [CI]
    uses: ./.github/workflows/test.yml
    secrets: inherit

  # Continuous Deployment (CD)
  CD:
    needs: [Tests]
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup DockerHub credentials
      - name: Setup Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            geraldobl58/webapp:v${{ github.run_number }}
            geraldobl58/webapp:latest

  # Deploy

  deploy-development:
    needs: [CD]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      K8S_NAMESPACE: development
    # with:
    #   environment-name: development
    #   environment-url: http://209.38.187.239

  # deploy-staging:
  #   needs: [CD]
  #   uses: ./.github/workflows/deploy.yml
  #   secrets: inherit
  #   with:
  #     environment-name: staging
  #     environment-url: http://165.227.240.220

  # deploy-production:
  #   needs: [CD]
  #   uses: ./.github/workflows/deploy.yml
  #   secrets: inherit
  #   with:
  #     environment-name: producao
  #     environment-url: http://165.227.240.221

  # Notifications
  # Notify:
  #   needs: [CI, Tests, CD, deploy-development, deploy-staging, deploy-production]
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Notify on success
  #     - name: Notify Success
  #       if: success()
  #       uses: slackapi/slack-github-action@v1.23.0
  #       with:
  #         payload: |
  #           {
  #             "text": "✅ CI/CD Pipeline completed successfully!\n\nDeployment Status:\n- Development: Success\n- Staging: Success\n- Production: Success\n\nCommit: ${{ github.sha }}\nBranch: ${{ github.ref_name }}"
  #           }
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  #     # Notify on failure
  #     - name: Notify Failure
  #       if: failure()
  #       uses: slackapi/slack-github-action@v1.23.0
  #       with:
  #         payload: |
  #           {
  #             "text": "❌ CI/CD Pipeline failed!\n\nFailed Jobs:\n${{ join(needs.*.result, '\n') }}\n\nCommit: ${{ github.sha }}\nBranch: ${{ github.ref_name }}\n\nPlease check the logs for more details."
  #           }
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
