name: CI/CD Pipeline

on:
  workflow_call:
    # inputs:
    #   K8S_NAMESPACE:
    #     required: true
    #     type: string
    #     default: development

jobs:
  deploy:
    name: Deploy in Kubernetes
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

       # Set Context
      - name: Apply Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}

      # Set Kubeconfig
      - name: Set Kubeconfig
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/ingress.yaml
            k8s/namespace.yaml
          images: geraldobl58/front-devops:v${{ github.run_number }}
