name: CI/CD Pipeline

on:
  workflow_call:
    # inputs:
    #   environment-name:
    #     required: true
    #     type: string
    #   environment-url:
    #     required: true
    #     type: string

jobs:
  deploy:
    name: Deploy in Kubernetes
    runs-on: ubuntu-latest
    # environment:
    #   name: ${{ inputs.environment-name }}
    #   url: ${{ inputs.environment-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configure Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            geraldobl58/webapp:v${{ github.run_number }}


      # - name: Notify Deployment Failure
      #   if: failure()
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     payload: |
      #       {
      #         "text": "❌ ${{ inputs.environment-name }} Deployment Failed!\n\nEnvironment: ${{ inputs.environment-name }}\nCommit: ${{ github.sha }}\nBranch: ${{ github.ref_name }}\n\nPlease check the logs for more details."
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      # Notifications
      # - name: Notify Success
      #   if: success()
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     payload: |
      #       {
      #         "text": "✅ CI/CD Pipeline completed successfully!\n\nDeployment Status:\n- Development: Success\n- Staging: Success\n- Production: Success\n\nCommit: ${{ github.sha }}\nBranch: ${{ github.ref_name }}"
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      # # Notify on failure
      # - name: Notify Failure
      #   if: failure()
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     payload: |
      #       {
      #         "text": "❌ CI/CD Pipeline failed!\n\nFailed Jobs:\n${{ join(needs.*.result, '\n') }}\n\nCommit: ${{ github.sha }}\nBranch: ${{ github.ref_name }}\n\nPlease check the logs for more details."
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}